import type { Metadata } from "next";
import Script from "next/script";
import { Geist, IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Providers from "@/context/providers";

const geist = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  variable: "--font-arabic",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Platvo AI Agent",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const analyticsDomain = (() => {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || process.env.BETTER_AUTH_URL;
    if (!appUrl) return "www.platvo.com";
    try {
      return new URL(appUrl).hostname;
    } catch {
      return appUrl.replace(/^https?:\/\//, "").replace(/\/$/, "");
    }
  })();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geist.variable} ${ibmPlexSansArabic.variable} font-sans antialiased`}
      >
        <Providers>{children}</Providers>
        <Script
          defer
          data-website-id="dfid_93RSrfFYx3dF668UWcHiO"
          data-domain={analyticsDomain}
          src="https://datafa.st/js/script.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
